name: 'pr'

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, closed]

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: validate
        run: |
          .github/scripts/validate.sh

      - name: build
        run: |
          docker run \
            --interactive -v $(pwd):/workspace gcr.io/kaniko-project/executor:latest \
            --context . --dockerfile ./Dockerfile \
            --destination=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA \
            --no-push --tar-path image.tar

      - name: debug
        run: |
          ls -lah .

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: push
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
        run: |
          docker image load --input image.tar
          docker image tag $GITHUB_REPOSITORY:$GITHUB_SHA $GITHUB_REPOSITORY:$IMAGEVERSION
          docker push $GITHUB_REPOSITORY:$IMAGEVERSION


