name: 'pr'

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, closed]

permissions:
  packages: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: validate
        run: |
          .github/scripts/validate.sh

      - name: build
        run: |
          docker run \
            --interactive -v $(pwd):/workspace gcr.io/kaniko-project/executor:latest \
            --context . --dockerfile ./Dockerfile \
            --destination=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA \
            --no-push --tar-path image.tar

      - name: debug
        run: |
          ls -la .
          docker image load --input image.tar
          docker image list

      - name: install crane
        run: |
          curl -L -o crane.tar.gz https://github.com/google/go-containerregistry/releases/download/v0.19.1/go-containerregistry_Linux_x86_64.tar.gz
          tar -xvf crane.tar.gz
          cp crane /usr/local/bin/
          crane version

      - name: push
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
        run: |
          ls -la .



#             docker image load --input image.tar.gz # this will output the original image name
# docker image tag original-registry.example.org/original-image-name:0.0.1 new-registry.example.com/new-image-name:0.0.1
# docker push new-registry.example.com/new-image-name

      # - name: Login to Github Packages
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${GITHUB_ACTOR}
      #     password: ${{ secrets.PAT }}


