name: 'pr'

on:
  pull_request:


permissions:
  packages: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: validate
        run: |
          .github/scripts/validate.sh

      - name: build
        run: |
          docker run \
          --interactive -v $(pwd):/workspace gcr.io/kaniko-project/executor:latest \
          --context . --dockerfile ./Dockerfile \
          -cache=true --cache-repo $GITHUB_REPOSITORY \
          --destination=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA \
          --no-push --tar-path image.tar



      # - name: Login to Github Packages
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${GITHUB_ACTOR}
      #     password: ${{ secrets.PAT }}


