name: 'pr'

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: validate
        run: |
          .github/scripts/validate.sh

      - name: build
        run: |
          /kaniko/executor --context . --dockerfile ./Dockerfile --cache=true --cache-repo $GITHUB_REPOSITORY --destination $GITHUB_REPOSITORY:$GITHUB_SHA



      # - name: Login to Github Packages
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${GITHUB_ACTOR}
      #     password: ${{ secrets.PAT }}


